### ISSUE TITLE
Tracking issue: planned breaking changes in v2

### ISSUE THREAD

**Issue by vweevers** [Level/abstract-level#47]
In order of significance:

- [x] https://github.com/Level/abstract-level/pull/50
  - [x] Replace use of `process.nextTick()` with `queueMicrotask()`
- [x] https://github.com/Level/abstract-level/pull/49
- [x] https://github.com/Level/abstract-level/pull/45
  - [x] Follow-up: https://github.com/Level/abstract-level/pull/53
- [x] ~~Remove `batch`, `put` and `del` events~~ (postponed)
- [x] https://github.com/Level/abstract-level/pull/51
- [x] https://github.com/Level/abstract-level/issues/13
- [x] https://github.com/Level/abstract-level/pull/54
- [x] ~~Support hooks and events on `db.clear()`. I don't know how yet, but may require breaking changes.~~ (postponed)
- [x] ~~Remove `_checkKey()` and `_checkValue()`, an `abstract-leveldown` leftover that has questionable value because after these methods are called, we run keys and values through encodings. In `level-transcoder` we should throw if the json encoding returns `undefined`, as a replacement for `undefined` checks. Other encodings don't need such checks.~~ (postponed)
- [x] https://github.com/Level/abstract-level/pull/48
- [x] ~~Throw error in default private API methods that must be overridden.~~ (postponed; can be semver-minor)
- [x] https://github.com/Level/abstract-level/pull/56 (not breaking per se)
- [x] https://github.com/Level/abstract-level/pull/52

These won't necessarily land in a single major version. I wanted a place to list them and allow people to object.

**Comment by vweevers** [comment]
I did a quick test on `memory-level`, replacing `_put(key, value, options, callback)` with `async _put(key, value, options)`. As a result, `await db.put(key, value)` is 2x faster!

```
$ level-bench plot put
benchmark put on memory-level@1.0.0 win32 x64
node@16.9.1 n=1M concurrency=4 valueSize=100B keys=random values=random

1  memory-level#v2    69565 ops/s ±8.83%  fastest
2  memory-level#main  33750 ops/s ±8.07%  +51.14%
```

**Comment by vweevers** [comment]
Removed a bunch of items from the list above, to keep the release manageable (see [`v2/UPGRADING.md`](https://github.com/Level/abstract-level/blob/v2/UPGRADING.md) for current content).

**Comment by vweevers** [comment]
Done; remaining items can go into a future release.
